### PR TITLE
get_namespace fix.

### PR DESCRIPTION
**Pull request by ichristen**
Get namespace now looks at the bottom of the stack for the correct file, and breaks the while loop early to avoid prepending `Modules_`.

### CODE REVIEW

**Comment by ichristen** [comment]
The last commit (e5544f6) could cause big issues if the user has an @ somewhere above the CommandCenter folder. Whether this is better or worse than ignoring /@class/private/file.m cases (which currently do not exist) is up the the Pull Request Approver.

**Comment by ichristen** [comment]
A better fix might have knowledge of the CC path, but that means that CC would have to be loaded and there would have to be yet another case for running drivers independently (without this knowledge).

**Comment by mwalsh161** [comment]
The only path info that is necessary is whatever MATLAB's path is. A better use of the builtin `what` does precisely this from what I understand. We don't need to choose between two edge cases - this should be solvable with just a bit more work.

**Comment by mwalsh161** [comment]
As discussed in slack, but for sake of a record - we realized this is impossible due to the ambiguity of the stack. Inheritance vs calling a member of a class is impossible to differentiate. I will change to provide the full classname as an input using either `class(obj)` or `mfilename('class')` for static methods.

**Pull request merged**
